controllers:
    resource: ../../src/Controller/
    type: annotation

admin_controllers:
    prefix: /admin
    resource: ../../src/Controller/Admin
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
